name: chrome
description: An interop library for accessing the Chrome API for extensions and apps
version: 0.0.2
authors:
  - nazarkalytiuk@gmail.com
# homepage: https://www.example.com

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  js: ^0.6.0
  meta: ^1.1.8

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
